### PR TITLE
Add .match(router) method that returns a route without invoking a callback

### PR DESCRIPTION
**Pull request by marcbachmann**
This pull request contains a first part of https://github.com/choojs/nanorouter/pull/8 without introducing any big changes. We'll first need to release https://github.com/yoshuawuyts/wayfarer/pull/64 to get that working with the published module.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
This looks good once `wayfarer` lands! :D

**Comment by marcbachmann** [comment]
@yoshuawuyts I updated the wayfarer dependency. So this would be ready to merge.
I'll also quickly do the PR for the api change mentioned in #12 . It's up to you whether you want to release this using a minor bump.

edit: here's the pr for the api change: https://github.com/choojs/nanorouter/pull/13. It also includes this commit at the moment. So you can decide whether you want to merge this one first, do a minor bump or directly merge the other one with the major bump.

**Review by yoshuawuyts — APPROVED** [review]
Rad!

**Comment by yoshuawuyts** [comment]
`v2.2.0` :tada:

**Pull request merged**
